#!/bin/bash
#
# THIS SCRIPT IS GENERATED BY MXENV.
# CHANGES MADE IN THIS FILE MAY BE LOST.
#
# Clean development environment


to_remove=(
    constraints-mxdev.txt
    requirements-mxdev.txt
    .coverage
    htmlcov
    docs/html
    bin
    include
    lib64
    lib
    pyvenv.cfg
    share
    openldap
)

for item in "${to_remove[@]}"; do
    if [ -e "$item" ]; then
        rm -rf "$item"
    fi
done



exit 0
