#!/bin/bash
#
# THIS SCRIPT IS GENERATED BY MXENV.
# CHANGES MADE IN THIS FILE MAY BE LOST.
#
# Install system dependencies


sudo apt-get install -y \
    build-essential \
    curl \
    libsasl2-dev \
    libssl-dev \
    libdb-dev \
    libltdl-dev



exit 0
