#!/bin/bash
#
# THIS SCRIPT IS GENERATED BY MXENV.
# CHANGES MADE IN THIS FILE MAY BE LOST.
#
# Install virtual environment


set -e

python3 -m venv .
./bin/pip install -U pip setuptools wheel

openldap="$(realpath openldap)"
./bin/pip install \
--no-use-pep517 \
--global-option=build_ext \
--global-option="-I$openldap/include" \
--global-option="-L$openldap/lib" \
--global-option="-R$openldap/lib" \
python-ldap

./bin/pip install -r requirements-mxdev.txt



exit 0
