name: Test conestack

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

env:
  FORCE_COLOR: "1"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.7"
          - "3.8"
          - "3.9"

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: make system-dependencies

      - name: Install project
        run: make project-install

      - name: Run tests
        run: make coverage

      - name: Upload HTML coverage report if check failed.
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report-${{ matrix.python }}
          path: htmlcov
          if-no-files-found: ignore
