name: Test conestack

on:
  push:
    branches:
      - 2.0
  workflow_dispatch:
    branches:
      - 2.0

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - uses: actions/checkout@v4

      - name: Install environment
        run: make install

      - name: Run tests an collect code coverage
        run: make coverage
