name: Test conestack
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.7"
    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: make system-dependencies

      - name: Install project
        run: |
          make openldap
          make python-ldap
          make project-install

      - name: Run tests
        run: make test
